---
- name: Installing Octopus Tentacle
  hosts: all
  tasks:
    - name: Download the Octopus Tentacle installer
      win_get_url:
        url: https://download.octopusdeploy.com/octopus/Octopus.Tentacle.5.0.13-x64.msi
        dest: '%TEMP%\Octopus.Tentacle.5.0.13-x64.msi'

    - name: Install the Octopus Tentacle MSI
      win_package:
        path: '%TEMP%\Octopus.Tentacle.5.0.13-x64.msi'
        arguments:
          - /install
          - /quiet
          - /norestart